# Generated by Django 5.1.5 on 2025-01-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_dimensions_parcel_recipient_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='size',
            field=models.CharField(default='Nieznany rozmiar', max_length=20),
        ),
    ]
