# Generated by Django 5.1.5 on 2025-01-22 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_parcel_order_parcel_current_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='status',
            field=models.CharField(choices=[('NEW', 'Nowe'), ('PICKED_UP', 'Kurier odebrał paczkę'), ('SORTING', 'Paczka jest na sortowni'), ('OUT_FOR_DELIVERY', 'Wydana do doręczenia'), ('DELIVERED', 'Doręczona')], default='NEW', max_length=20),
        ),
    ]
