# Generated by Django 5.1.5 on 2025-01-22 22:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_parcel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='tracking_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
