# Generated by Django 5.1.5 on 2025-01-22 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_parcel_tracking_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcel',
            name='current_lat',
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='current_lng',
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='status',
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='tracking_number',
        ),
        migrations.AddField(
            model_name='parcel',
            name='order',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parcel', to='orders.order'),
            preserve_default=False,
        ),
    ]
