replicaCount: 1

image:
  repository: localhost/courier-app
  pullPolicy: IfNotPresent
  tag: "v1"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  host: "kurier.local"
  path: "/"
  pathType: Prefix
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: "1Gi"
  mountPath: "/app/persistent_data"
